# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

{{- if and .Values.kubernetes.gatewayAPI.enabled .Values.kubernetes.gatewayAPI.upstreamSettingsPolicy.enabled }}
apiVersion: gateway.nginx.org/v1alpha1
kind: UpstreamSettingsPolicy
metadata:
  name: {{ template "am-all-in-one.fullname" . }}-upstream-settings-policy
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
  - group: ""
    kind: Service
    name: {{ template "am-all-in-one.fullname" . }}-am-service
  loadBalancingMethod: {{ .Values.kubernetes.gatewayAPI.upstreamSettingsPolicy.loadBalancingMethod | quote }}
{{- end }}
